version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: turbodiesel-backend
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=False
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - internal

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: turbodiesel-frontend
    restart: always
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.turbodiesel.rule=Host(`luanmienam.devoverflow.xyz`)"
      - "traefik.http.routers.turbodiesel.entrypoints=web,websecure"
      - "traefik.http.routers.turbodiesel.tls=true"
      - "traefik.http.routers.turbodiesel.tls.certresolver=mytlschallenge"
      - "traefik.http.services.turbodiesel.loadbalancer.server.port=80"

volumes:
  static_volume:
  media_volume:

networks:
  internal:
  traefik:
    external: true
    name: traefik
