services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=admin@devoverflow.xyz"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - traefik_letsencrypt:/letsencrypt
    networks:
      - traefik

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: turbodiesel-backend
    restart: always
    env_file:
      - backend/.env
    environment:
      - DEBUG=False
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - internal

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_BASE_URL: /api/v1
    container_name: turbodiesel-frontend
    restart: always
    expose:
      - "80"
    ports:
      - "5175:80"
    depends_on:
      - backend
    volumes:
      - media_volume:/usr/share/nginx/media:ro
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.turbodiesel-http.rule=Host(`luanmienam.devoverflow.xyz`)"
      - "traefik.http.routers.turbodiesel-http.entrypoints=web"
      - "traefik.http.routers.turbodiesel-http.middlewares=turbodiesel-https-redirect"
      - "traefik.http.middlewares.turbodiesel-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.turbodiesel.rule=Host(`luanmienam.devoverflow.xyz`)"
      - "traefik.http.routers.turbodiesel.entrypoints=websecure"
      - "traefik.http.routers.turbodiesel.tls=true"
      - "traefik.http.routers.turbodiesel.tls.certresolver=mytlschallenge"
      - "traefik.http.services.turbodiesel.loadbalancer.server.port=80"

volumes:
  traefik_letsencrypt:
  static_volume:
  media_volume:

networks:
  internal:
  traefik:
    external: true
    name: traefik
