# Generated by Django 6.0.6 on 2026-06-09 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangMay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True, verbose_name='Tên hãng máy')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'hang_may',
                'ordering': ['ten'],
            },
        ),
        migrations.CreateModel(
            name='HangSx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True, verbose_name='Tên hãng SX')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'hang_sx',
                'ordering': ['ten'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Thành công'), ('PARTIAL', 'Một phần'), ('FAILED', 'Thất bại')], max_length=20)),
                ('products_created', models.PositiveIntegerField(default=0)),
                ('products_updated', models.PositiveIntegerField(default=0)),
                ('customers_created', models.PositiveIntegerField(default=0)),
                ('customers_updated', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'import_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NhaXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nha_xe', models.CharField(max_length=300, verbose_name='Tên nhà xe')),
                ('dien_thoai', models.CharField(blank=True, default='', max_length=20, verbose_name='Điện thoại')),
                ('dia_chi', models.TextField(blank=True, default='', verbose_name='Địa chỉ')),
                ('gio_nhan', models.CharField(blank=True, default='', max_length=100, verbose_name='Giờ nhận')),
                ('ghi_chu', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nha_xe',
                'ordering': ['ten_nha_xe'],
            },
        ),
        migrations.CreateModel(
            name='ThuongHieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True, verbose_name='Tên thương hiệu')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'thuong_hieu',
                'ordering': ['ten'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_kh', models.CharField(max_length=50, unique=True, verbose_name='Mã KH')),
                ('ten_kh', models.CharField(max_length=300, verbose_name='Tên khách hàng')),
                ('dien_thoai', models.CharField(blank=True, default='', max_length=20, verbose_name='Điện thoại')),
                ('phan_loai', models.CharField(choices=[('VIP', 'Khách VIP'), ('ƯU_ĐÃI', 'Khách ưu đãi'), ('NGOẠI_LỆ', 'VIP ngoại lệ'), ('CHƯA_PL', 'Chưa phân loại')], default='CHƯA_PL', max_length=20, verbose_name='Phân loại')),
                ('dia_chi', models.TextField(blank=True, default='', verbose_name='Địa chỉ')),
                ('tinh_tp', models.CharField(blank=True, default='', max_length=100, verbose_name='Tỉnh/TP')),
                ('ghi_chu', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nha_xe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='products.nhaxe')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['ten_kh'],
                'indexes': [models.Index(fields=['ten_kh'], name='customers_ten_kh_aa79c5_idx'), models.Index(fields=['dien_thoai'], name='customers_dien_th_d5480d_idx'), models.Index(fields=['phan_loai'], name='customers_phan_lo_099d13_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('turbo', 'Turbo đầy đủ'), ('ruot', 'Ruột turbo')], default='turbo', max_length=10, verbose_name='Loại sản phẩm')),
                ('ma_vt', models.CharField(max_length=100, verbose_name='Mã VT')),
                ('model_turbo', models.CharField(blank=True, default='', max_length=300, verbose_name='Model Turbo')),
                ('ma_dong_co', models.CharField(blank=True, default='', max_length=300, verbose_name='Mã động cơ')),
                ('oem_part_no', models.TextField(blank=True, default='', verbose_name='OEM Part No')),
                ('dac_diem', models.TextField(blank=True, default='', verbose_name='Đặc điểm')),
                ('ung_dung', models.TextField(blank=True, default='', verbose_name='Ứng dụng')),
                ('ghi_chu', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('gia_vip', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá VIP')),
                ('gia_uu_dai', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá ưu đãi')),
                ('gia_dai_ly', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá đại lý')),
                ('gia_dl_10', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá ĐL+10%')),
                ('cg_duoi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='CG Ø Dưới')),
                ('cg_dinh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='CG Ø Đỉnh')),
                ('cg_so', models.CharField(blank=True, default='', max_length=20, verbose_name='CG Số')),
                ('cl_duoi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='CL Ø Dưới')),
                ('cl_dinh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='CL Ø Đỉnh')),
                ('cl_so', models.CharField(blank=True, default='', max_length=20, verbose_name='CL Số')),
                ('sheet_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Sheet gốc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hang_may', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.hangmay')),
                ('hang_sx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.hangsx')),
                ('thuong_hieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.thuonghieu')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['ma_vt'],
                'indexes': [models.Index(fields=['ma_vt'], name='products_ma_vt_52149a_idx'), models.Index(fields=['model_turbo'], name='products_model_t_ebc4ef_idx'), models.Index(fields=['loai'], name='products_loai_bc10e6_idx'), models.Index(fields=['hang_may'], name='products_hang_ma_fcf589_idx'), models.Index(fields=['thuong_hieu'], name='products_thuong__777b72_idx'), models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx')],
            },
        ),
    ]
