# Generated by Django 6.0.6 on 2026-06-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hinh_anh',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Hình ảnh'),
        ),
    ]
