# Generated by Django 6.0.6 on 2026-06-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_fix_loai_varchar_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='Số báo giá')),
                ('quote_date', models.DateField(auto_now_add=True, verbose_name='Ngày báo giá')),
                ('customer_name', models.CharField(max_length=300, verbose_name='Tên KH (snapshot)')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='ĐT KH (snapshot)')),
                ('gia_ap_dung', models.CharField(max_length=50, verbose_name='Loại giá áp dụng')),
                ('tong_cong', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Tổng cộng')),
                ('product_count', models.PositiveIntegerField(default=0, verbose_name='Số lượng SP')),
                ('nhan_vien', models.CharField(blank=True, default='', max_length=100, verbose_name='Nhân viên báo giá')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='products.customer')),
            ],
            options={
                'db_table': 'quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_vt', models.CharField(max_length=100, verbose_name='Mã VT')),
                ('ten_hang', models.CharField(blank=True, default='', max_length=500, verbose_name='Tên hàng')),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá')),
                ('so_luong', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('thanh_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Thành tiền')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='products.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.quotation')),
            ],
            options={
                'db_table': 'quotation_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quote_date'], name='quotations_quote_d_43196c_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer'], name='quotations_custome_3c961a_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['created_at'], name='quotations_created_ec533b_idx'),
        ),
    ]
