# Generated by Django 6.0.6 on 2026-06-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_quotation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='ghi_chu',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DA_GUI', 'Đã gởi'), ('DA_CHOT', 'Đã chốt'), ('THUA', 'Thua')], default='DA_GUI', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status'], name='quotations_status_5ae774_idx'),
        ),
    ]
