# Generated by Django 5.2.15 on 2026-06-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_quotation_status_ghichu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='danh_sach_hinh_anh',
            field=models.JSONField(blank=True, default=list, verbose_name='Danh sách hình ảnh'),
        ),
    ]
