# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_danh_sach_hinh_anh'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='excel_file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ten file Excel'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='excel_file_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Duong dan file Excel'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='excel_file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Dung luong file Excel'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='excel_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thoi diem tao file Excel'),
        ),
    ]
