# Generated by Django 5.2.15 on 2026-07-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_quotation_excel_file_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phan_loai',
            field=models.CharField(choices=[('VIP', 'Khách VIP'), ('ƯU_ĐÃI', 'Khách ưu đãi'), ('ĐẠI_LÝ', 'Khách đại lý'), ('GARA', 'Gara sửa chữa'), ('NGOẠI_LỆ', 'VIP ngoại lệ'), ('CHƯA_PL', 'Chưa phân loại')], default='CHƯA_PL', max_length=20, verbose_name='Phân loại'),
        ),
    ]
