# Generated by Django 5.2.15 on 2026-07-31 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_loai_enum'),
        ('products', '0007_fix_loai_varchar_length'),
        ('products', '0012_alter_customer_phan_loai'),
    ]

    operations = [
    ]
